name: flutter_base
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  drift: ^2.8.2
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  get_it: ^7.6.0
  dio: ^5.2.1+1
  flutter_dotenv: ^5.1.0
  pretty_dio_logger: ^1.3.1
  uuid: ^3.0.7
  bcrypt: ^1.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  encrypt: ^5.0.1
  flutter_bloc: ^8.1.3
  responsive_builder: ^0.7.0
  lucide_icons: ^0.244.0
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.8.3
  build_runner: ^2.4.5

flutter:
  uses-material-design: true
  generate: true